//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// HSChat_Client.rc에서 사용되고 있습니다.
//
#define IDR_MENU                        4
#define IDR_MENU_USER                   4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FORMVIEW_SIGNIN             101
#define IDD_HSCHAT_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_FORMVIEW_WAITING            103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_MAKEROOM             133
#define IDD_FORMVIEW_CHATROOM           134
#define IDD_FORMVIEW_SEARCHID           135
#define IDD_FORMVIEW_SEARCHPW           136
#define IDD_FORMVIEW_SIGNUP             137
#define IDD_FORMVIEW_MYINFO             138
#define IDD_DIALOG_FRIENDSLIST          139
#define IDD_FORMVIEW_FRIENDS_LIST       140
#define IDD_DIALOG_FRIENDADD            144
#define IDC_PICTURE_CONTROL             1000
#define IDC_STATIC_HSCHAT               1001
#define IDC_STATIC_SIGNIN_STATE         1002
#define IDC_STATIC_ID                   1003
#define IDC_BUTTON_MYINFO               1004
#define IDC_BUTTON_WATING_MYINFO        1004
#define IDC_STATIC_PW                   1005
#define IDC_BUTTON_LOGOUT               1006
#define IDC_STATIC_SEARCHPW_ID          1006
#define IDC_BUTTON_WATING_LOGOUT        1006
#define IDC_BUTTON_EXIT                 1007
#define IDC_STATIC_SIGNUP_NICKNAME      1007
#define IDC_BUTTON_WATING_EXIT          1007
#define IDC_EDIT_SIGNIN_ID              1008
#define IDC_STATIC_SIGNUP_PW            1008
#define IDC_EDIT_SIGNIN_PW              1009
#define IDC_STATIC_SIGNUP_PWOK          1009
#define IDC_LIST_ROOM                   1010
#define IDC_LIST_WATING_ROOM            1010
#define IDC_BUTTON_SIGNIN_SIGNUP        1011
#define IDC_LIST_WAITING_FRIENDS        1012
#define IDC_BUTTON_SIGNIN_SIGNIN        1013
#define IDC_BUTTON_SEARCHID             1014
#define IDC_BUTTON_FRIENDS              1015
#define IDC_BUTTON_WATING_FRIENDS       1015
#define IDC_BUTTON_SIGNIN_SEARCHID      1016
#define IDC_BUTTON_SEARCHPW             1017
#define IDC_BUTTON_SEARCHPW_CANCEL      1017
#define IDC_STATIC_CHATROOM             1018
#define IDC_STATIC_ROOMLIST             1019
#define IDC_STATIC_USERLIST             1020
#define IDC_BUTTON_SIGNIN_SEARCHPW      1021
#define IDC_BUTTON_CHATROOM_INVITE      1022
#define IDC_STATIC_FRIENDSLIST          1023
#define IDC_BUTTON_CHATROOM_SEND        1024
#define IDC_BUTTON_MAKEROOM_CANCEL      1025
#define IDC_BUTTON_CHATROOM_QUIT        1026
#define IDC_EDIT_SEARCHID_NAME          1026
#define IDC_BUTTON_MAKEROOM             1027
#define IDC_EDIT_SEARCHID_BIRTH         1027
#define IDC_BUTTON_CHATROOM_MSGDOWN     1028
#define IDC_BUTTON_SEARCHID_CANCEL      1028
#define IDC_STATIC_MAKEROOM_ROOMNAME    1029
#define IDC_EDIT_SEARCHID_PHONE         1029
#define IDC_EDIT_CHATROOM_RECVMSG       1030
#define IDC_STATIC_SEARCHID_NAME        1030
#define IDC_EDIT_SEARCHID_BIRTH_ID      1030
#define IDC_STATIC_MAKEROOK_NUM         1031
#define IDC_STATIC_SEARCHID_BIRTH       1031
#define IDC_EDIT_CHATROOM_SENDMSG       1032
#define IDC_STATIC_SEARCHPW_NAME        1032
#define IDC_STATIC_SEARCHID_PHONE       1032
#define IDC_EDIT_MAKEROOM_NAME          1033
#define IDC_STATIC_SEARCHPW_BIRTH       1033
#define IDC_LIST_CHATROOM_USERLIST      1034
#define IDC_EDIT_SEARCHPW_NAME          1034
#define IDC_EDIT_MAKEROOM_NUM           1035
#define IDC_EDIT_SEARCHPW_BIRTH         1035
#define IDC_RADIO_PUBLIC                1036
#define IDC_BUTTON_SEARCHPW_OK          1036
#define IDC_RADIO_PRIVATE               1037
#define IDC_BUTTON_SEARCHID_OK          1037
#define IDC_EDIT_SEARCHPW_PHONE         1037
#define IDC_EDIT_SEARCHPW_ID            1038
#define IDC_EDIT_SIGNUP_NICKNAME        1039
#define IDC_STATIC_SEARCHPW_PHONE       1039
#define IDC_EDIT_SIGNUP_PW              1040
#define IDC_EDIT_SEARCHPW_ID4           1041
#define IDC_EDIT_SIGNUP_PWOK            1041
#define IDC_STATIC_SIGNUP_NAME          1042
#define IDC_STATIC_SIGNUP_BIRTH         1043
#define IDC_STATIC_SIGNUP_ID            1044
#define IDC_EDIT_SIGNUP_NAME            1045
#define IDC_EDIT_SIGNUP_BIRTH           1046
#define IDC_EDIT_SIGNUP_ID              1047
#define IDC_BUTTON_SIGNUP_OK            1048
#define IDC_BUTTON_SIGNUP_CANCEL        1049
#define IDC_BUTTON_FRIENDS_ADD          1049
#define IDC_STATIC_SIGNUP_PHONE         1050
#define IDC_BUTTON_WATING_MAKEROOM      1050
#define IDC_EDIT_SIGNUP_PHONE           1051
#define IDC_BUTTON_WATING_MAKEROOM2     1051
#define IDC_BUTTON_WATING_UPDATE        1051
#define IDC_EDIT_MYINFO_NAME            1052
#define IDC_EDIT_MYINFO_BIRTH           1053
#define IDC_STATIC_MYINFO_NAME          1054
#define IDC_STATIC_MYINFO_BIRTH         1055
#define IDC_STATIC_MYINFO_ID            1056
#define IDC_EDIT_MYINFO_ID              1057
#define IDC_EDIT_MYINFO_PHONE           1058
#define IDC_STATIC_MYINFO_PHONE         1059
#define IDC_EDIT_MYINFO_NICKNAME        1060
#define IDC_STATIC_MYINFO_NICKNAME      1061
#define IDC_EDIT_MYINFO_PW              1062
#define IDC_STATIC_MYINFO_PW            1063
#define IDC_STATIC_MYINFO_PWOK          1064
#define IDC_EDIT_MYINFO_PWOK            1066
#define IDC_BUTTON_MYINFO_CANCEL        1067
#define IDC_BUTTON_MYINFO_OK            1068
#define IDC_BUTTON_MYINFO_DELETE        1069
#define IDC_DATETIMEPICKER_BIRTH        1070
#define IDC_PICTURE_FRIENDSLIST         1071
#define IDC_LIST_FRIENDLIST_FRIENDS     1073
#define IDC_BUTTON_FRIENDS_DELETE       1074
#define IDC_STATIC_FRIENDADD_NICKNAME   1075
#define IDC_EDIT_FRIENDADD_NICKNAME     1076
#define IDC_BUTTON_FRIENDADD_CANCEL     1077
#define IDC_BUTTON_FRIENDADD_OK         1078
#define IDC_CHATRROM_MENUBUTTON         1088
#define IDC_CHATROOM_COMBO              1089
#define IDC_SEARCHID_BIRTH              1091
#define IDC_SEARCHPW_BIRTH              1092
#define ID_DD_DD                        32771
#define ID_DD_DD32772                   32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID__32775                       32775
#define ID_MENU_WHISPER                 32776
#define ID_MENU_                        32777
#define ID_MENU_ASSIGN                  32778
#define ID__MENU_BAN                    32779
#define ID_MENU_TOWHISPER               32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
